### ISSUE TITLE
Legal from 1.0: 3.10.5 Additional steps and enhancements: OS steps 

### ISSUE THREAD

**Issue by xml-project** [xproc/steps#21]
# 3.10.5 Additional steps and enhancements: OS steps 

>This is an aggregation of the discussion on "3.10.5 Additional steps and enhancements: OS steps" ([Issue 58 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/58))

**Opened by: ndw on 2014-08-22, 18:43h**

## ndw said on 2014-08-22, 18:43h:

The vocabulary of steps available in XProc is extensible. Users and implementors have developed additional steps. For example, to support pipelines that produce EPUB documents or manipulate files on disk. It is worth considering which, if any, new steps should be elevated to the XProc namespace. The candidates include, but are not limited to: 

Operating system steps (p:env, ...)? 

	On 2014-08-22, 18:43h: ndw added requirement should labels.

	On 2014-08-25, 22:28h: ndw added this to the XProc 2.0 LC milestone.

	On 2015-06-11, 13:03h: xquery added the steps label.

**Comment by eriksiegel** [comment]
Ah, well. I've created a PR that adds the OS steps to the main step library.

But in the previous comment @ndw writes we have general agreement on putting them in a *separate* and *optional* library. Do we? Why separate and optional? IMHO this and all the other EXProc steps are excellent candidates for the core step library.

Maybe this opens up old discussion, sorry for that.

**Comment by eriksiegel** [comment]
And since you all approved the PR, we are no longer talking about a separate spec?
