### ISSUE TITLE
p:dishwasher

### ISSUE THREAD

**Issue by Gertone** [xproc/steps#6]
I like to propose a new step that could replace p:sink

`  <p:dishwasher>
       <p:input port="source"/>                  
       <p:output port="result"/>       
       <p:option name="loading-type" 
              select="'Gerrit-style'"/>   
     </p:dishwasher>`

**Comment by xml-project** [comment]
Not sure whether it would not be better to assign type="xs:QName" for "loading-type", so we could put the method in a namespace, e.g. "le-tex:Gerit-style" or "sgml-guru:ari-style".
But may be a boolean "sorted=(true | false)" might suffice our needs to. ;-))

**Comment by ndw** [comment]
From my experience with dishwashers, we're missing options for random chance of dishes that come out insufficiently clean, number of said dishes, that weird blue liquid the manufacturer suggests that you add, quantity of detergent, length of washing cycle, heat or air dry, and energy saver options at least.

Do we need social media options?

Suggest more requirements gathering.

**Comment by Gertone** [comment]
It does prove that (although in the vicinity of a dishwasher) a diner-table (even gathering some SMEs) is not necessarily a guarantee for detailed specification

**Comment by xquery** [comment]
"Gerrit-style" | "Ari-style" does not reflect that this option is setting order eg. I propose
 
<p:option name="sort-type" select="'Gerrit'"/>

**Comment by mkraetke** [comment]
I would like to propose that if the map of cups couldn't be aligned with the sorting order, a fatal error should be thrown which causes the xproc processor to immediately end the execution of the pipeline. This is such a serious issue, no respectable person want's this error to be caught by a p:catch or p:finally. I mean we are XML guys, we are for draconian error handling, aren't we?

**Comment by xml-project** [comment]
Since @gimsieke is our SME here, I assigned this issue to him. Please feel free to close it, if you think the discussion is finished.

**Comment by xquery** [comment]
fastest sort is random (or to be precise, in computing, psuedo random) so I think 'ari' sort should be the default as 'faster is always better then correct'.

**Comment by gimsieke** [comment]
I think the required functionality can easily be implemented in XSLT. Therefore I don’t see the need to introduce a `p:dishwasher` step in the standard step library. But we still can (and should) use `c:spoon`, `c:cup` etc. documents (rather than maps) to model the content, possibly already with a loading manifest in order to specify the arrangement of the dishes:
```xml
<c:dishwasher-manifest>
  <c:rack xml:id="r1" position="bottom">
    <c:lane type="spikes" position="left">
      <c:plate diameter="20cm" clean="false"/>
    </c:lane>
    <c:basket position="center front">
      <c:basket-compartment xml:id="b1" position="left rear">
        <c:teaspoon clean="false"/>
      </c:basket-compartment>
    </c:basket>
  </c:rack>
  <c:rack position="middle">
  …
  </c:rack>
  …
</c:dishwasher-manifest>
```
If it is not a standard step, we probably should use a vocabulary in a different namespace, such as `http://xproc.org/ns/DishWasherML`

You can then declare:

```xml
<p:declare-step type="dw:dishwasher"
   xmlns:dw="http://xproc.org/ns/DishWasherML"
   xmlns:some="urn:X:some">
  <p:input port="source" primary="true" sequence="true">
    <p:documentation>DishwasherML documents, for ex. with a 'dw:plate' or `dw:knife`,
      or `dw:dishwasher-manifest` top-level element</p:documentation>
  </p:input>
  <p:input port="detergent" sequence="true">
    <some:pod/>
  </p:input>
  <p:input port="rinse-aid" sequence="true"/>
  <p:input port="salt" sequence="true"/>
  <p:input port="water" href="dishwasher-water-supply.xml"/>
  <p:output port="result" sequence="true"/>
  <p:option name="temperature" select="'50degC'" as="xs:string"/>
  <p:option name="anal" select="false()" as="xs:boolean">
    <p:documentation>https://en.wikipedia.org/wiki/Anal_retentiveness</p:documentation>
  </p:option>

  <p:validate-with-relax-ng name="check-loading">
    <p:with-input href="../schema/dishwasherml.rnc"/>
  </p:validate-with-relax-ng>

  <p:if test="$anal">
    <p:validate-with-schematron name="pedantically-check-loading">
      <p:documentation>Will make sure that the input is a single 
        dw:dishwasher-manifest document in which the dishes are 
        arranged “reasonably well” (not Ari-style).</p:documentation>
      <p:with-input href="../schema/gerrit.sch"/>
    </p:validate-with-schematron>
  </p:if>
 
  <p:xslt>
    <p:input port="source" pipe="source detergent rinse-aid salt water">
      <p:documentation>The XSLT sees all inputs in its default collection. 
        It needs to figure out which is which (cup, water, detergent, …) by 
        looking at the element names.</p:documentation>
    </p:input>
    <p:input port="stylesheet" href="../xsl/default-dishwashing-procedure.xsl"/>
    <p:with-option name="parameters" select="map {'temperature':$temperature}"/>
  <p:xslt>
</p:declare-step>
```
and use the step:
```xml
<p:declare-step name="wash-n-stow">
  <p:input port="source" primary="true"/>
  <p:import-functions href="../xsl/dishwasher-functions.xsl" 
    content-type="application/xslt+xml" 
    namespace="http://xproc.org/ns/DishWasherML"/>
  <dw:dishwasher name="wash-it"/>
  <p:split-sequence test="dw:type(.)='utensil'" name="split"/>
  <p:store href="drawer.xml"/>
  <p:store href="cupboard.xml" pipe="not-matched@split"/>
</p:declare-step>
```
And then you can read the drawer and cupboard again and then validate whether the dishes have been stored correctly. (Or create a custom unload/store step that first creates a storage manifest from the unsorted dishwasher output sequence.)

**Comment by gimsieke** [comment]
The ordering won’t be applied by the dishwasher step, but it needs to be applied when creating the dishwasher loading / cupboard/drawer storage manifests. 
This can be done by editing manifests manually, but there could also be other XSLTs that create optimal load/store manifests from a given input sequence. Some of the XSLTs will be more sophisticated than others, and these will create loading/storage patterns that will easily pass the most anal Schematrons.
